const docprofile = [
  {
    name: "Dr. John Doe",
    specialization: "Surgeon",
    experience: "10+ years",
    location: "New York, USA",
    rating: 4.8,
    reviews: 120,
    hospital: "New York General Hospital",
    contact: "+1 234 567 890",
    availability: "Mon-Fri, 9 AM - 5 PM",
  },
  {
    name: "Dr. Emily Smith",
    specialization: "Cardiologist",
    experience: "15+ years",
    location: "Los Angeles, USA",
    rating: 4.9,
    reviews: 200,
    hospital: "LA Heart Center",
    contact: "+1 987 654 321",
    availability: "Tue-Sat, 10 AM - 6 PM",
  },
  {
    name: "Dr. Arjun Patel",
    specialization: "Neurologist",
    experience: "12+ years",
    location: "Mumbai, India",
    rating: 4.7,
    reviews: 150,
    hospital: "Mumbai Neuro Hospital",
    contact: "+91 99876 54321",
    availability: "Mon-Fri, 10 AM - 4 PM",
  },
  {
    name: "Dr. Lisa Wong",
    specialization: "Pediatrician",
    experience: "8+ years",
    location: "Singapore",
    rating: 4.6,
    reviews: 98,
    hospital: "Singapore Kids Care",
    contact: "+65 6543 2109",
    availability: "Mon-Sat, 9 AM - 1 PM",
  },
  {
    name: "Dr. Ahmed El-Sayed",
    specialization: "Orthopedic",
    experience: "14+ years",
    location: "Cairo, Egypt",
    rating: 4.9,
    reviews: 175,
    hospital: "Cairo Orthopedic Institute",
    contact: "+20 1012345678",
    availability: "Sun-Thu, 11 AM - 6 PM",
  },
  {
    name: "Dr. Maria Gonzalez",
    specialization: "Dermatologist",
    experience: "9+ years",
    location: "Madrid, Spain",
    rating: 4.5,
    reviews: 110,
    hospital: "Madrid Skin Center",
    contact: "+34 912 345 678",
    availability: "Mon-Fri, 10 AM - 3 PM",
  },
  {
    name: "Dr. Kenji Nakamura",
    specialization: "Endocrinologist",
    experience: "11+ years",
    location: "Tokyo, Japan",
    rating: 4.7,
    reviews: 130,
    hospital: "Tokyo Diabetes Clinic",
    contact: "+81 80 1234 5678",
    availability: "Mon-Fri, 8 AM - 2 PM",
  },
  {
    name: "Dr. Fatima Al-Mansoori",
    specialization: "Gynecologist",
    experience: "13+ years",
    location: "Dubai, UAE",
    rating: 4.8,
    reviews: 160,
    hospital: "Dubai Women’s Hospital",
    contact: "+971 50 987 6543",
    availability: "Sun-Thu, 9 AM - 5 PM",
  },
  {
    name: "Dr. James Anderson",
    specialization: "Oncologist",
    experience: "17+ years",
    location: "Toronto, Canada",
    rating: 4.9,
    reviews: 210,
    hospital: "Toronto Cancer Center",
    contact: "+1 416 123 4567",
    availability: "Mon-Fri, 10 AM - 6 PM",
  },
  {
    name: "Dr. Chantal Dubois",
    specialization: "Psychiatrist",
    experience: "10+ years",
    location: "Paris, France",
    rating: 4.6,
    reviews: 95,
    hospital: "Paris Mental Health Clinic",
    contact: "+33 1 23 45 67 89",
    availability: "Mon-Fri, 9 AM - 4 PM",
  },
];
export default docprofile;
